name: flutter_webapi_first_course
description: Projeto do primeiro curso de WebAPI da Formação Flutter

publish_to: 'none'

version: 1.0.0+1 # Versionamento correto: "1.0.0" é o versionName, "+1" é o versionCode.

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  google_fonts: ^4.0.5
  http: ^1.2.2
  http_interceptor: ^2.0.0
  logger: ^2.5.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
